### ISSUE TITLE
Some problems w.r.t the files and code

### ISSUE THREAD

**Issue by graytowne** [mouna99/dien#3]
Hi, first of all, thanks for releasing the code. While I found there exist some problems that might need to be resolved:

1. Missing two files (reviews-info and reviews-info) which are required for training the models.
2. In [line 131](https://github.com/mouna99/dien/blob/master/script/train.py#L131) of train.py, it called deepFM, but it isn't implemented.
3. The code is incompatible with TensorFlow > v1.4, as something changed in rnn_cell_impl.py (after v.14, TF abandoned the use of _Linear() when implementing RNNCells).

**Comment by mouna99** [comment]
Thank you for pointing out the problems. 
1. The problem of missing data has been fixed.
2. We had implemented the deepFM but the performance is not as good as the original paper reported, so we do not plan to open this implementation. If you have a good implementation, you are welcome to contribute code to this project. 
3. Since when we did this research our tf version was 1.4, the modifications were made based on this, without considering the later changes. We'll consider compatibility with the new versions if we have time.
